sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t abinmathayi/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true abinmathayi/react-test npm run test
after_success:
  - docker build -t abinmathayi/multi-client ./client
  - docker build -t abinmathayi/multi-nginx ./nginx
  - docker build -t abinmathayi/multi-server ./server
  - docker build -t abinmathayi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push abinmathayi/multi-client
  - docker push abinmathayi/multi-nginx
  - docker push abinmathayi/multi-server
  - docker push abinmathayi/multi-worker